replicaCount: 1

image:
  front:
    repository: nginx
    tag: latest
  backend:
    repository: my-registry.io/my-application/backend
    tag: 1.0

service:
  front:
    type: LoadBalancer
    port: 80
  back:
    type: ClusterIP
    port: 8080

env:
  SPRING_POSTGRES_USERNAME: "myapplication"
  SPRING_POSTGRES_PASSWORD: "M3P@ssw0rd!"
  SPRING_POSTGRES_URL: "jdbc:postgresql://my-db-test.io:5432/mydatabase"