apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-application.fullname" . }}-front
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-application.fullname" . }}-front
  template:
    metadata:
      labels:
        app: {{ include "my-application.fullname" . }}-front
    spec:
      containers:
        - name: front
          image: "{{ .Values.image.front.repository }}:{{ .Values.image.front.tag }}"
          ports:
            - containerPort: 80