apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-application.fullname" . }}-back
spec:
  type: {{ .Values.service.back.type }}
  ports:
    - port: {{ .Values.service.back.port }}
      targetPort: 8080
  selector:
    app: {{ include "my-application.fullname" . }}-back