apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-application.fullname" . }}-front
spec:
  type: {{ .Values.service.front.type }}
  ports:
    - port: {{ .Values.service.front.port }}
      targetPort: 80
  selector:
    app: {{ include "my-application.fullname" . }}-front